services:
  strapi:
    container_name: strapi
    build:
      context: ./cms/docker
      args:
        NODE_VERSION: ${NODE_VERSION}
    restart: on-failure:3
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_VERSION}
    volumes:
      - ./cms:/strapi
    ports:
      - '1337:1337'